defaults:
  -
    scope:
      path: "**/*.html"
    values:
      layout: "default"

mediaurl: "https://media.githubusercontent.com/media/krisl/learnrussian.rt.com/master"
cssurl: "https://media.githubusercontent.com/media/krisl/learnrussian.rt.com/master/s/css/"
baseurl: "/learnrussian.rt.com"
